version: '3'

services:
  app:
    image: romeucamurca/go-mongo-romeu:1.0.0
    container_name: go-app
    ports:
      - "9080:9080" 
    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017" 
    environment:
      - MONGO_DB_HOST="localhost"
    volumes:
      - mongodb_data:/data/db 

volumes:
  mongodb_data:
